# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import country_pb2 as country__pb2


class CountryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_all = channel.unary_unary(
                '/Country/get_all',
                request_serializer=country__pb2.CountryEmpty.SerializeToString,
                response_deserializer=country__pb2.CountryMultipleResponse.FromString,
                )


class CountryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=country__pb2.CountryEmpty.FromString,
                    response_serializer=country__pb2.CountryMultipleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Country', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Country(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Country/get_all',
            country__pb2.CountryEmpty.SerializeToString,
            country__pb2.CountryMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
